spring:
  application:
    name: ms-sysfinan-cadastro
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3307/${MYSQL_SCHEMA}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

opentracing:
  jaeger:
    enable-w3c-propagation: true
    enable-128-bit-traces: true
    expand-exception-logs: true
    service-name: ms-sysfinan-cadastro
    udp-sender:
      host: localhost
      port: 6831
    sampler-type: const
    sampler-param: 1
    log-spans: true